<?php

namespace app\components;

use yii\base\Widget;

class Moneycard extends Widget
{
    public $sum;
    public $date_enable;
    public $type;
    public $currency;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        if($this->sum === null)
        {
            $this->sum = "0";
        }
        if($this->date_enable === null)
        {
            $this->date_enable = false;
        }
        if($this->type === null)
        {
            $this->type = "Общая сумма";
        }
        if($this->currency === null)
        {
            $this->currency = "грн";
        }
    }

    public function run()
    {
        return $this->render('moneycard',[
            'sum' => $this->sum,
            'currency' => $this->currency,
            'type' => $this->type
        ]);
    }
}